### ISSUE TITLE
Header line of CoNLL dataset

### ISSUE THREAD

**Issue by lunayach** [MI2DataLab/WildNLP#3]
When I tried to load the CoNLL dataset using `dataset.load()`, I encountered the following error:

```
Traceback (most recent call last):
  File "new.py", line 6, in <module>
    dataset.load('eng.train')
  File "/home/mayank/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/wildnlp/datasets/base.py", line 10, in func_wrapper
    return func(*args, **kwargs)
  File "/home/mayank/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/wildnlp/datasets/conll.py", line 47, in load
    sample += line
UnboundLocalError: local variable 'sample' referenced before assignment
```
This was because of the header line in my version of CoNLL dataset being `-DOCSTART- -X- -X- O` instead of `-DOCSTART- -X- O O`. This condition is being checked in this line: https://github.com/MI2DataLab/WildNLP/blob/0eb7951b8a6a74281a9bb1e03e01a6bc7af3b33d/wildnlp/datasets/conll.py#L35

Maybe, the Header Line should not be hardcoded to accommodate different versions.

**Comment by aslucki** [comment]
It's solved now, thanks @lunayach! :)
